get_route:
    path: api/v1/hello
    controller: App\Controller\ApiController::handleGet
    methods: GET

post_route:
    path: api/v1/hello
    controller: App\Controller\ApiController::handlePost
    methods: POST

test_page:
    path: /
    controller: App\Controller\ApiController::index
